import structlog

from agents.ai_client import ask
from agents.base import AgentResult, AgentStatus, BaseAgent
from agents.github_client import GitHubRepoClient
from api.services.github_auth import get_github_auth_service

logger = structlog.get_logger(__name__)

README_SYSTEM = """\
You are a technical writer. Given a codebase structure and key files, generate a complete README.md.

Include: project description, architecture overview, quick start, environment variables, API endpoints, development guide, and license section.
Use clear markdown. Be concise but complete.
Return only the markdown content, no extra commentary.
"""

CHANGELOG_SYSTEM = """\
You are a technical writer. Given a list of commits (format: hash message), generate a CHANGELOG.md entry
following Keep-a-Changelog format for the changes included.

Return only the markdown content for the new version section.
"""


class DocsAgent(BaseAgent):
    name = "docs_agent"

    async def run(self, *, event_type: str, payload: dict, installation_id: int) -> AgentResult:
        if event_type != "pull_request":
            return self._skip("only runs on pull_request events")

        action = payload.get("action")
        if action not in ("opened", "synchronize"):
            return self._skip(f"ignoring action={action}")

        pr = payload.get("pull_request", {})
        repo = payload.get("repository", {})
        pr_number = pr.get("number")
        head_sha = pr.get("head", {}).get("sha")
        head_branch = pr.get("head", {}).get("ref", "main")
        base_branch = pr.get("base", {}).get("ref", "main")
        owner, repo_name = repo.get("full_name", "/").split("/", 1)

        try:
            auth = get_github_auth_service()
            token = await auth.get_installation_token(installation_id)
            gh = GitHubRepoClient(token, owner, repo_name)

            actions: list[str] = []
            pr_url = None

            # Check if README needs updating
            readme = await gh.get_file("README.md", ref=head_sha)
            changed_files = await gh.get_pr_files(pr_number)

            # Only regenerate README if structural files changed
            structural_files = {
                "api/main.py",
                "docker-compose.yml",
                "requirements.txt",
                "pyproject.toml",
            }
            needs_readme = any(f in structural_files for f in changed_files)

            if needs_readme:
                # Build codebase context
                context = ""
                for path in ["api/main.py", "docker-compose.yml", "requirements.txt"]:
                    repo_file = await gh.get_file(path, ref=head_sha)
                    if repo_file:
                        context += f"\n--- {path} ---\n{repo_file.content[:2000]}"

                new_readme = await ask(README_SYSTEM, f"Codebase:\n{context}", max_tokens=2048)

                branch_name = f"agent/docs-{pr_number}"
                try:
                    await gh.create_branch(branch_name, from_ref=head_branch)
                except Exception as exc:
                    logger.debug("Branch may already exist", error=str(exc))

                await gh.create_or_update_file(
                    path="README.md",
                    content=new_readme,
                    message="docs: update README [agent]",
                    branch=branch_name,
                    sha=readme.sha if readme else None,
                )
                actions.append("updated_readme")

                pr_url = await gh.create_pull_request(
                    title=f"docs: update README for PR #{pr_number}",
                    body="Documentation update generated by Docs Agent.",
                    head=branch_name,
                    base=base_branch,
                )

            logger.info("Docs agent complete", actions=actions)
            return self._result(AgentStatus.SUCCESS, actions=actions, pr_url=pr_url)

        except Exception as exc:
            logger.error("Docs agent failed", error=str(exc))
            return self._result(AgentStatus.FAILED, error=str(exc))
